select -all;
global proc Duplicator( float $randRange ){
     for ($i = 0; $i <10; $i++){         
         float $randNumX = rand (- $randRange, $randRange ) ;         
         float $randNumZ = rand (- $randRange, $randRange ) ;  
        string $house[0] = `ls -shapes`;      
        duplicate -returnRootsOnly;                  
        move -relative $randNumX 0 $randNumZ $house ;     
     }    
}
Duplicator(20)